branches:
  only:
    - integration
    - /-ci$/
    - /-cit$/

os: linux
dist: trusty

language: c

services:
  - docker

jobs:
  # The first five jobs should be the canaries in the coal mine, i.e. the most likely to fail if there are problems in the code.
  # They should also be a good mix of unit, integration, and documentation tests.
  #
  # In general tests should be ordered from slowest to fastest for the first five jobs (the maximum concurrent jobs allowed), then
  # slowest to fastest for the rest of the tests. This does not make a difference for testing a single commit, but when multiple
  # commits are being tested it is best to have the slowest jobs first so that as jobs become available they will tackle the slowest
  # tests first.
  include:
    # All unit (without coverage) and integration tests for 32-bit
    - env: PGB_CI="test --vm=u12 --param=no-performance"

    # Debian/Ubuntu documentation
    - env: PGB_CI=" doc --vm=u18"

    # Valgrind is disabled due to some platform-specific issues in getpwuid() and getgrgid() that do not seem to be pgBackRest bugs.
    # Run in a different timezone to check time tests.
    - arch: pp64le
      dist: bionic
      env:
        - PGB_CI="test --vm=none --param=no-valgrind --param=tz=America/New_York"
      services:

    # All integration tests
    - env: PGB_CI="test --vm=co6 --param=build-package --param=module=mock --param=module=real"

    # All integration tests
    - env: PGB_CI="test --vm=u18 --param=build-package --param=module=mock --param=module=real"

    # All unit tests (with coverage) on the newest gcc available
    - env: PGB_CI="test --vm=f32 --param=c-only --param=no-performance"

    # RHEL/CentOS 6 documentation
    - env: PGB_CI=" doc --vm=co6"

    # All integration tests
    - env: PGB_CI="test --vm=co7 --param=module=mock --param=module=real"

    # RHEL/CentOS 7 documentation
    - env: PGB_CI=" doc --vm=co7"

    # Basic unit tests only because arm64 is slow. Coverage testing is also disabled to save time.
    - arch: arm64
      dist: bionic
      env:
        - PGB_CI="test --vm=none --param=no-coverage --param=module=command --param=module=storage"
      services:

install:
  - umask 0022 && cd ~ && pwd && whoami && umask && groups
  - df -Th && top -bn1

script:
  - ${TRAVIS_BUILD_DIR?}/test/travis.pl ${PGB_CI?}
